name: Create TXZ on Release and Upload to Archive
on:
  release:
    types: [published]

jobs:
  releaseTxz:
    name: Create Release Txz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: |
          echo "repo=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT
          NAME=$(awk 'match($0, /^<!ENTITY name "(.*)">$/) {print substr($0, RSTART+15, RLENGTH-17)}' *.plg)
          echo "plugname=$NAME" >> $GITHUB_OUTPUT
          echo "plugdir=$(awk 'match($0, /^<!ENTITY plugdir "(.*)">$/) {print substr($0, RSTART+18, RLENGTH-20)}' *.plg | sed "s,&name;,$NAME," | sed 's/^\///')" >> $GITHUB_OUTPUT
      - name: Make TXZ
        id: tar
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          PLUGNAME: ${{ steps.vars.outputs.plugname }}
          PLUGDIR: ${{ steps.vars.outputs.plugdir }}
        run: |
          tar --xz -cf "archive/$PLUGNAME-$RELEASE_VERSION.txz" --transform "s,^src/,$PLUGDIR/," $(find src/*)
          echo "md5=$(md5sum "archive/$PLUGNAME-$RELEASE_VERSION.txz" | awk '{ print $1 }')" >> $GITHUB_OUTPUT
      - name: Add Release to .plg file
        env:
          GITHUB_REPO: ${{ steps.vars.outputs.repo }}
          TAR_MD5: ${{ steps.tar.outputs.md5 }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: |
          sed -i "s/<!ENTITY version \".*\">/<!ENTITY version \"$RELEASE_VERSION\">/" *.plg
          sed -i "s/<!ENTITY md5 \".*\">/<!ENTITY md5 \"$TAR_MD5\">/" *.plg
          sed -i "s/<!ENTITY github \".*\">/<!ENTITY github \"${GITHUB_REPOSITORY//\//\\\/}\">/" *.plg
          sed -i "s|    <CHANGES>|    <CHANGES>\n### $RELEASE_VERSION\n${RELEASE_NOTES//$'\n'/\\$'\n'}|" *.plg
      - uses: actions/upload-artifact@v4
        with:
          name: test-txz
          path: |
            archive/easybackup-${{ github.event.release.tag_name }}.txz
            *.plg
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
