name: Create TXZ on Release and Upload to Archive
on:
  release:
    types: [published]

jobs:
  releaseTxz:
    name: Create Release Txz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "repo=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT
      - name: Add Release to .plg file
        env:
          GITHUB_REPO: ${{ steps.vars.outputs.repo }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: |
          sed -i "s/<!ENTITY version \".*\">/<!ENTITY version \"$RELEASE_VERSION\">/" easybackup.plg
          sed -i "s|    <CHANGES>|    <CHANGES>\n###$RELEASE_VERSION\n${RELEASE_NOTES//$'\n'/\\$'\n'}|" easybackup.plg
      - name: Make TXZ
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          find src/*
          tar --xz -cf "archive/easybackup-$RELEASE_VERSION.txz" --transform 's,^src/,usr/local/emhttp/plugins/easybackup/,' --exclude='src/' src
      - uses: actions/upload-artifact@v4
        with:
          name: test-txz
          path: |
            archive/easybackup-${{ github.event.release.tag_name }}.txz
            easybackup.plg
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
