name: Create TXZ on Release and Upload to Archive
on:
  release:
    types: [published]

jobs:
  releaseTxz:
    name: Create Release Txz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set output
        id: vars
        run: echo "repo=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT
      - name: Add Release to .plg file
        env:
          GITHUB_REPO: ${{ steps.vars.outputs.repo }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          RELEASE_NOTES: ${{ github.event.release.body }}
        run: |
          echo "Repo: $GITHUB_REPO"
          echo "Version: $RELEASE_VERSION"
          echo "Notes: $RELEASE_NOTES"
          sed -i "s/<!ENTITY version \".*\">/<!ENTITY version \"$RELEASE_VERSION\">/" easybackup.plg
          sed -i "s|    <CHANGES>|    <CHANGES>\n###$RELEASE_VERSION\n$RELEASE_NOTES|" easybackup.plg
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: easybackup.plg
      # - name: Zip Folder
      #   run: |
      #     cd ../
      #     zip -r <repository_name>.zip <repository_name> -x ".git/*" ".github/*"
