name: Create TXZ and Add To Release
on:
  release:
    types: [published]

jobs:
  releaseTxz:
    name: Create Txz and Release
    runs-on: ubuntu-latest
    env:
      PLUGNAME: easybackup
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Set output
        id: vars
        run: |
          echo "repo=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT
          awk 'match($0, /^<!ENTITY plugdir "(.*)">$/) {print substr($0, RSTART+18, RLENGTH-20)}' ${{ env.PLUGNAME }}.plg # | sed "s,&name;,${{ env.PLUGNAME }}," | sed 's/^\///'
          PLUGDIR=$(awk 'match($0, /^<!ENTITY plugdir "(.*)">$/) {print substr($0, RSTART+18, RLENGTH-20)}' ${{ env.PLUGNAME }}.plg | sed "s,&name;,${{ env.PLUGNAME }}," | sed 's/^\///')
          echo $PLUGDIR
          echo "plugdir=$PLUGDIR" >> $GITHUB_OUTPUT
      - name: Make TXZ
        id: tar
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          PLUGDIR: ${{ steps.vars.outputs.plugdir }}
        run: |
          tar --xz -cf "${{ env.PLUGNAME }}-$RELEASE_VERSION.txz" --transform "s,^src/,$PLUGDIR/," $(find src/*)
          echo "md5=$(md5sum "${{ env.PLUGNAME }}-$RELEASE_VERSION.txz" | awk '{ print $1 }')" >> $GITHUB_OUTPUT
      - name: Add Release Notes to .plg file
        env:
          RELEASE_NOTES: ${{ github.event.release.body }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          sed -i "s|    <CHANGES>|    <CHANGES>\n### $RELEASE_VERSION\n${RELEASE_NOTES//$'\n'/\\$'\n'}|" ${{ env.PLUGNAME }}.plg
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Add Release Notes for ${{ github.event.release.tag_name }}"
          add: "${{ env.PLUGNAME }}.plg"
      - name: Update .plg file before Attaching to Release
        env:
          TAR_MD5: ${{ steps.tar.outputs.md5 }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          sed -i "s/<!ENTITY version \".*\">/<!ENTITY version \"$RELEASE_VERSION\">/" ${{ env.PLUGNAME }}.plg
          sed -i "s/<!ENTITY md5 \".*\">/<!ENTITY md5 \"$TAR_MD5\">/" ${{ env.PLUGNAME }}.plg
          sed -i "s/<!ENTITY github \".*\">/<!ENTITY github \"${GITHUB_REPOSITORY//\//\\\/}\">/" ${{ env.PLUGNAME }}.plg
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PLUGNAME }}-${{ github.event.release.tag_name }}.txz
            ${{ env.PLUGNAME }}.plg
